In [ ]:
from numpy import array, zeros, float32

In [ ]:
def upper_tri_matrix(a: list, b: list) -> list:
    """_summary_

    Args:
        a (list): 2 d list
        b (list): 1 d list
    """
    a = array(a, dtype=float32)
    b = array(b, dtype=float32)

    for k in range(len(b) - 1):
        for i in range(k + 1, len(b)):
            coff = a[i, k] / a[k, k]

            for j in range(k, len(b)):
                a[i, j] = a[i, j] - coff * a[k, j]

            b[i] = b[i] - coff * b[k]

    return a, b


def vals(a, b):
    n = len(b)
    x = zeros(n, dtype=float32)
    x[n - 1] = b[n - 1] / a[n - 1, n - 1]
    for i in range(n - 2, -1, -1):
        sum_ = b[i]
        for j in range(i + 1, n):
            sum_ = sum_ - a[i, j] * x[j]

        x[i] = sum_ / a[i, i]

    return x

In [ ]:
from numpy import float32, array, append, copy, zeros, abs, shape, empty


class GuassEle:
    def __init__(self, A: list[list[float]], b: list[float]):
        """A x = b

        Args:
            A (list[list[float]]): 2 d square matrix
            b (list[float]): 1 d matrix or vector
        """
        self.A = array(A, dtype=float32)
        self.b = array(b, dtype=float32)
        self.solutions = self.vals()
        self.A_upper = self.upper_triangular_mtx()[0]
        self.b_upper = self.upper_triangular_mtx()[1]

    def upper_triangular_mtx(self):
        A = self.A.copy()
        b = self.b.copy()

        n = b.shape[0]
        for i in range(0, n - 1):
            if abs(A[i, i]) == 0:
                for k in range(i + 1, n):
                    if abs(A[k, i]) > abs(A[i, i]):
                        A[[i, k]] = A[[k, i]]
                        b[[i, k]] = b[[k, i]]
                        break

            for j in range(i + 1, n):
                m = A[j, i] / A[i, i]
                A[j, :] = A[j, :] - m * A[i, :]
                b[j] = b[j] - m * b[i]

        return A, b

    def __str__(self):
        return f"A -> {self.A}\nb -> {self.b}\nsolutions -> {self.solutions}\nA upper -> \n{self.A_upper}\nb_upper -> {self.b_upper}"

    def vals(self):
        A = self.upper_triangular_mtx()[0]
        b = self.upper_triangular_mtx()[1]

        n = b.shape[0]
        x = zeros(n, dtype=float32)
        x[n - 1] = b[n - 1] / A[n - 1, n - 1]
        for i in range(n - 2, -1, -1):
            sum_ = b[i]
            for j in range(i + 1, n):
                sum_ = sum_ - A[i, j] * x[j]

            x[i] = sum_ / A[i, i]

        return x

In [39]:
A = [[1, 2, -1, 1], [-1, 1, 2, -1], [2, -1, 2, 2], [1, 1, -1, 2]]
b = [6, 3, 14, 8]

vv = GuassEle(A, b)
vv.solutions
print(vv)

A -> [[ 1.  2. -1.  1.]
 [-1.  1.  2. -1.]
 [ 2. -1.  2.  2.]
 [ 1.  1. -1.  2.]]
b -> [ 6.  3. 14.  8.]
solutions -> [1. 2. 3. 4.]
A upper -> 
[[ 1.         2.        -1.         1.       ]
 [ 0.         3.         1.         0.       ]
 [ 0.         0.         5.6666665  0.       ]
 [ 0.         0.         0.         1.       ]]
b_upper -> [ 6.  9. 17.  4.]


In [ ]:
def solutions(a: list, b: list) -> list:
    a, b = upper_tri_matrix(a, b)
    return vals(a, b)


In [ ]:
a = [[1, 2, -1, 1], [-1, 1, 2, -1], [2, -1, 2, 2], [1, 1, -1, 2]]
b = [6, 3, 14, 8]

solutions(a, b)

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
import torch as th

In [ ]:
x = th.tensor(2.0, requires_grad=True)

y = th.tensor(4.0)

y = x**2
f = th.sigmoid(y)


In [41]:
f.backward()

In [46]:
y.backward

<bound method Tensor.backward of tensor(4., grad_fn=<PowBackward0>)>

In [ ]:
x, y, f

(tensor(2., requires_grad=True),
 tensor(4., grad_fn=<PowBackward0>),
 tensor(0.9820, grad_fn=<SigmoidBackward0>))

In [ ]:
f * (1 - f) * 2 * x

tensor(0.0707, grad_fn=<MulBackward0>)

In [48]:
0.0177 * 4

0.0708

In [35]:
x.detach()

tensor(2.)